### PR TITLE
Add python 3.4 compatibility

### PR DESCRIPTION
**Pull request by jmaupetit**
It seems to work for both python 2.7 and python 3.4

### CODE REVIEW

**Comment by tdsmith** [comment]
This is great; thanks a lot!

**Comment by jmaupetit** [comment]
You are welcome :) Do you plan a new release pushed to PyPI soon?

**Comment by tdsmith** [comment]
Hmm, I think not yet; the formulas poet writes for python 3 have "lib/python2.7" hardcoded. I just opened #8; I'd like to resolve that first. I'll get to it maybe this weekend or you're welcome to take a crack at it. Essentially, the formula template needs python-version-specific content.

**Comment by jmaupetit** [comment]
I totally missed the thing. I'll try to take a look this week.

**Pull request closed without merging**
