### PR TITLE
Use `six` for python 2/3 compatibility

### PR DESCRIPTION
**Pull request by hwright**
This simplifies some existing imports statements and make additional compatibility easier.

### CODE REVIEW

**Comment by hwright** [comment]
@tdsmith Ping

**Comment by tdsmith** [comment]
Thanks. Does this make your life easier in some other way? I have conflicting feelings about adding dependencies, especially something like six or requests that gets used a lot by CLI apps that are likely to be installed with Homebrew. Adding more dependencies increases the risk of a dependency conflict between homebrew-pypi-poet itself and the target package. I'm not aware of packages that pin six, so I don't know that my concern is realistic, but I also don't expect poet to expand as a project, so I don't see a clear win in terms of maintenance burden here. What's your thinking?

**Comment by hwright** [comment]
I think `six` is ubiquitous enough that it shouldn't be a problem.  It's also been very stable, so people updating packages using `poet` are likely to have a recent version that works.

My primary motivation for this is that I'd like to add a feature which allows poet to consider packages in  repositories other than `pypi.python.org`, something akin to pip's `--extra-index-url` flag.  Doing so means catching exceptions which `urlopen` may throw, and that gets a bit uglier in a non-`six` world.  Still doable, but messy.

**Comment by tdsmith** [comment]
Ubiquity is both a mitigating and exacerbating factor. You could argue that to work reliably, poet needs to be compatible with all versions of its dependencies that have ever been released, because something in the dependency tree of a target might require a different version. Obviously the constraints are a little bit weaker in practice. Packages that aren't often used in CLI apps mostly don't matter because the probability of a conflict is low (which is the justification for jinja). OTOH, if something was incompatible with a new version of six, it would probably have to become compatible pretty quickly. So, six is probably fine, but there's also no real benefit to the existing code base.

Anyway, I'm not personally interested in maintaining a version of poet with that feature (#55); of course, you're welcome to fork poet.

I'll choose not to accept this PR in the spirit of conservatism ("if it ain't broke..."), but thanks for your time!

**Pull request closed without merging**
