### PR TITLE
Gracefully handle packages not in pypi

### PR DESCRIPTION
**Pull request by rickard-von-essen**
If you have a package that is not availible in PYPi poet will fail on:
```python
urlopen("https://pypi.python.org/pypi/{}/json".format(name))
```

This patch make poet continue but print the following resource stanza
```ruby
  # {{ resource.name }} not found, ignoring
```

We use Homebrew to distribute our internal tools and the packages are directly downloaded from private hosted git.

### CODE REVIEW

**Comment by tdsmith** [comment]
Hello! Sorry for the delay; I've been traveling. I'd be a little nervous about this approach since if any of your packages acquires a doppelganger on pypi the script will find the pypi script instead. Would some kind of blacklist regex list make sense?

**Comment by tdsmith** [comment]
— Alternatively, an option to specify a server other than pypi.python.org with the pypi API (devpi etc) would be straightforward.

**Comment by rickard-von-essen** [comment]
Maybe a blacklist is best. We don't use a private pip server. We pull our internal tools directly from git.

I'll updated the PR so it `poet` will take a new argument `-e` `--exclude` which will give you a way to just skip some packages.

**Comment by tdsmith** [comment]
It doesn't look like you pushed the branch to your fork; that sounds like a great solution though.

**Comment by rickard-von-essen** [comment]
@tdsmith I got interrupted. I'll file a new PR when I have some time to finish it but it might take some weeks.

**Pull request closed without merging**
